#ifndef HERBARY_LIB_TYPE_FLOAT32_COMPARE_H_INCLUDED
#define HERBARY_LIB_TYPE_FLOAT32_COMPARE_H_INCLUDED

#include "./meta_compare.h"

#include "herbary/lib/type/float32.h"

_HERBARY_LIB_TYPE_DEFN_COMPARE_FUNC_TYPE(float32, float32_t)

#endif // HERBARY_LIB_TYPE_FLOAT32_COMPARE_H_INCLUDED
