#ifndef HERBARY_LIB_TYPE_FLOAT64_COMPARE_H_INCLUDED
#define HERBARY_LIB_TYPE_FLOAT64_COMPARE_H_INCLUDED

#include "./meta_compare.h"

#include "herbary/lib/type/float64.h"

_HERBARY_LIB_TYPE_DEFN_COMPARE_FUNC_TYPE(float64, float64_t)

#endif // HERBARY_LIB_TYPE_FLOAT64_COMPARE_H_INCLUDED
