#ifndef HERBARY_LIB_TYPE_FLOAT128_COMPARE_H_INCLUDED
#define HERBARY_LIB_TYPE_FLOAT128_COMPARE_H_INCLUDED

#include "./meta_compare.h"

#include "herbary/lib/type/float128.h"

_DEFN_COMPARE_FUNC_TYPE(float128, float128_t)

#endif // HERBARY_LIB_TYPE_FLOAT128_COMPARE_H_INCLUDED
