#ifndef HERBARY_LIB_TYPE_INT64_COMPARE_H_INCLUDED
#define HERBARY_LIB_TYPE_INT64_COMPARE_H_INCLUDED

#include <stdint.h>

#include "./meta_compare.h"

_DEFN_COMPARE_FUNC_TYPE(int64, int64_t)

#endif // HERBARY_LIB_TYPE_INT64_COMPARE_H_INCLUDED
