#ifndef HERBARY_LIB_TYPE_INT8_COMPARE_H_INCLUDED
#define HERBARY_LIB_TYPE_INT8_COMPARE_H_INCLUDED

#include <stdint.h>

#include "./meta_compare.h"

_HERBARY_LIB_TYPE_DEFN_COMPARE_FUNC_TYPE(int8, int8_t)

#endif // HERBARY_LIB_TYPE_INT8_COMPARE_H_INCLUDED
