#ifndef HERBARY_LIB_TYPE_UINT64_COMPARE_H_INCLUDED
#define HERBARY_LIB_TYPE_UINT64_COMPARE_H_INCLUDED

#include <stdint.h>

#include "./meta_compare.h"

_HERBARY_LIB_TYPE_DEFN_COMPARE_FUNC_TYPE(uint64, uint64_t)

#endif // HERBARY_LIB_TYPE_UINT64_COMPARE_H_INCLUDED
