#ifndef HERBARY_LIB_TYPE_SORT_ORDER_H_INCLUDED
#define HERBARY_LIB_TYPE_SORT_ORDER_H_INCLUDED

typedef enum {
	SORT_ORDER_ASCENDANCY = 0,
	SORT_ORDER_DESCENDANCY = 2
} sort_order_t;

#endif // HERBARY_LIB_TYPE_SORT_ORDER_H_INCLUDED
