#ifndef HERBARY_LIB_UTIL_FLOAT128_COMPARE_H_INCLUDED
#define HERBARY_LIB_UTIL_FLOAT128_COMPARE_H_INCLUDED

#include "./meta_compare.h"

#include "herbary/lib/type/float128.h"

_HERBARY_LIB_UTIL_DEFN_COMPARE_FUNC(float128, float128_t)

#endif // HERBARY_LIB_UTIL_FLOAT128_COMPARE_H_INCLUDED
