#ifndef HERBARY_LIB_UTIL_FLOAT64_COMPARE_H_INCLUDED
#define HERBARY_LIB_UTIL_FLOAT64_COMPARE_H_INCLUDED

#include "./meta_compare.h"

#include "herbary/lib/type/float64.h"

_HERBARY_LIB_UTIL_DECL_COMPARE_FUNC(float64, float64_t)

#endif // HERBARY_LIB_UTIL_FLOAT64_COMPARE_H_INCLUDED
