#ifndef HERBARY_LIB_UTIL_INT16_COMPARE_H_INCLUDED
#define HERBARY_LIB_UTIL_INT16_COMPARE_H_INCLUDED

#include <stdint.h>

#include "./meta_compare.h"

_HERBARY_LIB_UTIL_DEFN_COMPARE_FUNC(int16, int16_t)

#endif // HERBARY_LIB_UTIL_INT16_COMPARE_H_INCLUDED
