#ifndef HERBARY_LIB_UTIL_INT32_COMPARE_H_INCLUDED
#define HERBARY_LIB_UTIL_INT32_COMPARE_H_INCLUDED

#include <stdint.h>

#include "./meta_compare.h"

_HERBARY_LIB_UTIL_DECL_COMPARE_FUNC(int32, int32_t)

#endif // HERBARY_LIB_UTIL_INT32_COMPARE_H_INCLUDED
