#ifndef HERBARY_LIB_UTIL_INT8_COMPARE_H_INCLUDED
#define HERBARY_LIB_UTIL_INT8_COMPARE_H_INCLUDED

#include <stdint.h>

#include "./meta_compare.h"

_DEFN_COMPARE_FUNC(int8, int8_t)

#endif // HERBARY_LIB_UTIL_INT8_COMPARE_H_INCLUDED
