#ifndef HERBARY_LIB_UTIL_UINT16_COMPARE_H_INCLUDED
#define HERBARY_LIB_UTIL_UINT16_COMPARE_H_INCLUDED

#include <stdint.h>

#include "./meta_compare.h"

_HERBARY_LIB_UTIL_DECL_COMPARE_FUNC(uint16, uint16_t)

#endif // HERBARY_LIB_UTIL_UINT16_COMPARE_H_INCLUDED
