#ifndef HERBARY_LIB_UTIL_GENERIC_SWAP_H_INCLUDED
#define HERBARY_LIB_UTIL_GENERIC_SWAP_H_INCLUDED

#include "./meta_swap.h"

_HERBARY_LIB_UTIL_DEFN_SWAP_FUNC(generic, void)

#endif // HERBARY_LIB_UTIL_GENERIC_SWAP_H_INCLUDED
