#ifndef HERBARY_LIB_UTIL_FLOAT128_SORT_H_INCLUDED
#define HERBARY_LIB_UTIL_FLOAT128_SORT_H_INCLUDED

#include "./meta_sort.h"

#include "herbary/lib/type/float128.h"

_DEFN_IS_SORTED_NO_SIZE_PARAM_FUNC(float128, float128_t)

#endif // HERBARY_LIB_UTIL_FLOAT128_SORT_H_INCLUDED
