#ifndef HERBARY_LIB_UTIL_FLOAT64_MERGE_SORT_H_INCLUDED
#define HERBARY_LIB_UTIL_FLOAT64_MERGE_SORT_H_INCLUDED

#include "./meta_sort.h"

#include "herbary/lib/type/float64.h"

_HERBARY_LIB_UTIL_DECL_SORT_NO_SIZE_PARAM_FUNC(float64, merge, float64_t)

#endif // HERBARY_LIB_UTIL_FLOAT64_MERGE_SORT_H_INCLUDED
