#ifndef HERBARY_LIB_UTIL_FLOAT32_QUICK_SORT_H_INCLUDED
#define HERBARY_LIB_UTIL_FLOAT32_QUICK_SORT_H_INCLUDED

#include "./meta_sort.h"

#include "herbary/lib/type/float32.h"

_HERBARY_LIB_UTIL_DECL_SORT_NO_SIZE_PARAM_FUNC(float32, quick, float32_t)

#endif // HERBARY_LIB_UTIL_FLOAT32_QUICK_SORT_H_INCLUDED
