#ifndef HERBARY_LIB_UTIL_FLOAT128_MERGE_SORT_H_INCLUDED
#define HERBARY_LIB_UTIL_FLOAT128_MERGE_SORT_H_INCLUDED

#include "./meta_sort.h"

#include "herbary/lib/type/float128.h"

_HERBARY_LIB_UTIL_DEFN_SORT_NO_SIZE_PARAM_FUNC(float128, merge, float128_t)

#endif // HERBARY_LIB_UTIL_FLOAT128_MERGE_SORT_H_INCLUDED
