#ifndef HERBARY_LIB_UTIL_INT16_QUICK_SORT_H_INCLUDED
#define HERBARY_LIB_UTIL_INT16_QUICK_SORT_H_INCLUDED

#include <stdint.h>

#include "./meta_sort.h"

_DEFN_SORT_NO_SIZE_PARAM_FUNC(int16, quick, int16_t)

#endif // HERBARY_LIB_UTIL_INT16_QUICK_SORT_H_INCLUDED
