#ifndef HERBARY_LIB_UTIL_INT16_SORT_H_INCLUDED
#define HERBARY_LIB_UTIL_INT16_SORT_H_INCLUDED

#include <stdint.h>

#include "./meta_sort.h"

_DEFN_IS_SORTED_NO_SIZE_PARAM_FUNC(int16, int16_t)

#endif // HERBARY_LIB_UTIL_INT16_SORT_H_INCLUDED
