#ifndef HERBARY_LIB_UTIL_INT32_QUICK_SORT_H_INCLUDED
#define HERBARY_LIB_UTIL_INT32_QUICK_SORT_H_INCLUDED

#include <stdint.h>

#include "./meta_sort.h"

_HERBARY_LIB_UTIL_DEFN_SORT_NO_SIZE_PARAM_FUNC(int32, quick, int32_t)

#endif // HERBARY_LIB_UTIL_INT32_QUICK_SORT_H_INCLUDED
