#ifndef HERBARY_LIB_UTIL_INT32_MERGE_SORT_H_INCLUDED
#define HERBARY_LIB_UTIL_INT32_MERGE_SORT_H_INCLUDED

#include <stdint.h>

#include "./meta_sort.h"

_DEFN_SORT_NO_SIZE_PARAM_FUNC(int32, merge, int32_t)

#endif // HERBARY_LIB_UTIL_INT32_MERGE_SORT_H_INCLUDED
