#ifndef HERBARY_LIB_UTIL_INT64_SORT_H_INCLUDED
#define HERBARY_LIB_UTIL_INT64_SORT_H_INCLUDED

#include <stdint.h>

#include "./meta_sort.h"

_HERBARY_LIB_UTIL_DECL_IS_SORTED_NO_SIZE_PARAM_FUNC(int64, int64_t)

#endif // HERBARY_LIB_UTIL_INT64_SORT_H_INCLUDED
