#ifndef HERBARY_LIB_UTIL_UINT16_MERGE_SORT_H_INCLUDED
#define HERBARY_LIB_UTIL_UINT16_MERGE_SORT_H_INCLUDED

#include <stdint.h>

#include "./meta_sort.h"

_DEFN_SORT_NO_SIZE_PARAM_FUNC(uint16, merge, uint16_t)

#endif // HERBARY_LIB_UTIL_UINT16_MERGE_SORT_H_INCLUDED
