#ifndef HERBARY_LIB_UTIL_UINT16_SORT_H_INCLUDED
#define HERBARY_LIB_UTIL_UINT16_SORT_H_INCLUDED

#include <stdint.h>

#include "./meta_sort.h"

_HERBARY_LIB_UTIL_DEFN_IS_SORTED_NO_SIZE_PARAM_FUNC(uint16, uint16_t)

#endif // HERBARY_LIB_UTIL_UINT16_SORT_H_INCLUDED
