#ifndef HERBARY_LIB_UTIL_UINT32_SORT_H_INCLUDED
#define HERBARY_LIB_UTIL_UINT32_SORT_H_INCLUDED

#include <stdint.h>

#include "./meta_sort.h"

_DEFN_IS_SORTED_NO_SIZE_PARAM_FUNC(uint32, uint32_t)

#endif // HERBARY_LIB_UTIL_UINT32_SORT_H_INCLUDED
