#ifndef HERBARY_LIB_UTIL_UINT64_MERGE_SORT_H_INCLUDED
#define HERBARY_LIB_UTIL_UINT64_MERGE_SORT_H_INCLUDED

#include <stdint.h>

#include "./meta_sort.h"

_HERBARY_LIB_UTIL_DECL_SORT_NO_SIZE_PARAM_FUNC(uint64, merge, uint64_t)

#endif // HERBARY_LIB_UTIL_UINT64_MERGE_SORT_H_INCLUDED
