#ifndef HERBARY_LIB_UTIL_FLOAT128_PRINT_H_INCLUDED
#define HERBARY_LIB_UTIL_FLOAT128_PRINT_H_INCLUDED

#include "./meta_print.h"

#include "herbary/lib/type/float128.h"

_HERBARY_LIB_UTIL_DECL_PRINT_FUNC(float128, float128_t)

#endif // HERBARY_LIB_UTIL_FLOAT128_PRINT_H_INCLUDED
