#ifndef HERBARY_LIB_UTIL_FLOAT32_PRINT_H_INCLUDED
#define HERBARY_LIB_UTIL_FLOAT32_PRINT_H_INCLUDED

#include "./meta_print.h"

#include "herbary/lib/type/float32.h"

_HERBARY_LIB_UTIL_DEFN_PRINT_FUNC(float32, float32_t)

#endif // HERBARY_LIB_UTIL_FLOAT32_PRINT_H_INCLUDED
