#ifndef HERBARY_LIB_UTIL_INT32_PRINT_H_INCLUDED
#define HERBARY_LIB_UTIL_INT32_PRINT_H_INCLUDED

#include <stdint.h>

#include "./meta_print.h"

_DEFN_PRINT_FUNC(int32, int32_t)

#endif // HERBARY_LIB_UTIL_INT32_PRINT_H_INCLUDED
