#ifndef HERBARY_LIB_UTIL_INT64_PRINT_H_INCLUDED
#define HERBARY_LIB_UTIL_INT64_PRINT_H_INCLUDED

#include <stdint.h>

#include "./meta_print.h"

_HERBARY_LIB_UTIL_DEFN_PRINT_FUNC(int64, int64_t)

#endif // HERBARY_LIB_UTIL_INT64_PRINT_H_INCLUDED
