#ifndef HERBARY_LIB_UTIL_UINT64_PRINT_H_INCLUDED
#define HERBARY_LIB_UTIL_UINT64_PRINT_H_INCLUDED

#include <stdint.h>

#include "./meta_print.h"

_HERBARY_LIB_UTIL_DECL_PRINT_FUNC(uint64, uint64_t)

#endif // HERBARY_LIB_UTIL_UINT64_PRINT_H_INCLUDED
