#ifndef HERBARY_LIB_UTIL_UINT32_PRINT_H_INCLUDED
#define HERBARY_LIB_UTIL_UINT32_PRINT_H_INCLUDED

#include <stdint.h>

#include "./meta_print.h"

_DEFN_PRINT_FUNC(uint32, uint32_t)

#endif // HERBARY_LIB_UTIL_UINT32_PRINT_H_INCLUDED
