#ifndef HERBARY_LIB_UTIL_UINT8_PRINT_H_INCLUDED
#define HERBARY_LIB_UTIL_UINT8_PRINT_H_INCLUDED

#include <stdint.h>

#include "./meta_print.h"

_HERBARY_LIB_UTIL_DECL_PRINT_FUNC(uint8, uint8_t)

#endif // HERBARY_LIB_UTIL_UINT8_PRINT_H_INCLUDED
